//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 11:17:30 PM IST 
//

package com.nagarro.codingcompetition.resources;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DOJ" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Skills" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DomainExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CommunicationsRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NAGP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="YearsOfExperience" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CurrentRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PreviousCustomerExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AvailableFromDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "record" })
@XmlRootElement(name = "resource-data")
public class ResourceData {

	protected List<ResourceData.Record> record;

	/**
	 * Gets the value of the record property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the record property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRecord().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ResourceData.Record }
	 * 
	 * 
	 */
	public List<ResourceData.Record> getRecord() {
		if (record == null) {
			record = new ArrayList<ResourceData.Record>();
		}
		return this.record;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DOJ" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="Skills" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DomainExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="CommunicationsRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="NAGP" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="YearsOfExperience" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
	 *         &lt;element name="CurrentRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="PreviousCustomerExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="AvailableFromDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "employeeID", "doj", "skills", "domainExperience", "rating",
			"communicationsRating", "nagp", "yearsOfExperience", "currentRole", "previousCustomerExperience",
			"availableFromDate" })
	public static class Record {

		@XmlElement(name = "EmployeeID", required = true)
		protected String employeeID;

		@XmlElement(name = "DOJ", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date doj;

		@XmlElement(name = "Skills", required = true)
		protected String skills;

		@XmlElement(name = "DomainExperience")
		protected String domainExperience;

		@XmlElement(name = "Rating", required = true)
		protected String rating;

		@XmlElement(name = "CommunicationsRating", required = true)
		protected String communicationsRating;

		@XmlElement(name = "NAGP", required = true)
		protected String nagp;

		@XmlElement(name = "YearsOfExperience", required = true)
		protected BigDecimal yearsOfExperience;

		@XmlElement(name = "CurrentRole")
		protected String currentRole;

		@XmlElement(name = "PreviousCustomerExperience")
		protected String previousCustomerExperience;

		@XmlElement(name = "AvailableFromDate", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date availableFromDate;

		/**
		 * Gets the value of the employeeID property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getEmployeeID() {
			return employeeID;
		}

		/**
		 * Sets the value of the employeeID property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setEmployeeID(String value) {
			this.employeeID = value;
		}

		/**
		 * Gets the value of the doj property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getDOJ() {
			return doj;
		}

		/**
		 * Sets the value of the doj property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setDOJ(Date value) {
			this.doj = value;
		}

		/**
		 * Gets the value of the skills property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSkills() {
			return skills;
		}

		/**
		 * Sets the value of the skills property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSkills(String value) {
			this.skills = value;
		}

		/**
		 * Gets the value of the domainExperience property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDomainExperience() {
			return domainExperience;
		}

		/**
		 * Sets the value of the domainExperience property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDomainExperience(String value) {
			this.domainExperience = value;
		}

		/**
		 * Gets the value of the rating property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRating() {
			return rating;
		}

		/**
		 * Sets the value of the rating property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRating(String value) {
			this.rating = value;
		}

		/**
		 * Gets the value of the communicationsRating property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCommunicationsRating() {
			return communicationsRating;
		}

		/**
		 * Sets the value of the communicationsRating property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCommunicationsRating(String value) {
			this.communicationsRating = value;
		}

		/**
		 * Gets the value of the nagp property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNAGP() {
			return nagp;
		}

		/**
		 * Sets the value of the nagp property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNAGP(String value) {
			this.nagp = value;
		}

		/**
		 * Gets the value of the yearsOfExperience property.
		 * 
		 * @return possible object is {@link BigDecimal }
		 * 
		 */
		public BigDecimal getYearsOfExperience() {
			return yearsOfExperience;
		}

		/**
		 * Sets the value of the yearsOfExperience property.
		 * 
		 * @param value
		 *            allowed object is {@link BigDecimal }
		 * 
		 */
		public void setYearsOfExperience(BigDecimal value) {
			this.yearsOfExperience = value;
		}

		/**
		 * Gets the value of the currentRole property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCurrentRole() {
			return currentRole;
		}

		/**
		 * Sets the value of the currentRole property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCurrentRole(String value) {
			this.currentRole = value;
		}

		/**
		 * Gets the value of the previousCustomerExperience property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPreviousCustomerExperience() {
			return previousCustomerExperience;
		}

		/**
		 * Sets the value of the previousCustomerExperience property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPreviousCustomerExperience(String value) {
			this.previousCustomerExperience = value;
		}

		/**
		 * Gets the value of the availableFromDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getAvailableFromDate() {
			return availableFromDate;
		}

		/**
		 * Sets the value of the availableFromDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setAvailableFromDate(Date value) {
			this.availableFromDate = value;
		}

	}
}

class DateAdapter extends XmlAdapter<String, Date> {

	private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd-mm-YYYY");

	@Override
	public String marshal(Date v) throws Exception {
		synchronized (dateFormat) {
			return dateFormat.format(v);
		}
	}

	@Override
	public Date unmarshal(String v) throws Exception {
		synchronized (dateFormat) {
			return dateFormat.parse(v);
		}
	}

}