//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 11:17:50 PM IST 
//

package com.nagarro.codingcompetition.openings;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RequestID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="ClientKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsKeyProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProjectDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ProjectStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="ProjectEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsKeyPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="YearsOfExperience" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="MandatorySkills" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ClientCommunication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RequestStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="AllocationEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "record" })
@XmlRootElement(name = "resource-data")
public class ResourceData {

	protected List<ResourceData.Record> record;

	/**
	 * Gets the value of the record property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the record property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRecord().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ResourceData.Record }
	 * 
	 * 
	 */
	public List<ResourceData.Record> getRecord() {
		if (record == null) {
			record = new ArrayList<ResourceData.Record>();
		}
		return this.record;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RequestID" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="ClientKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ProjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ProjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="IsKeyProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ProjectDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="ProjectStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="ProjectEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="IsKeyPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="YearsOfExperience" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
	 *         &lt;element name="MandatorySkills" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ClientCommunication" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="RequestStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="AllocationEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "requestID", "clientKey", "projectKey",
			"customerName", "projectName", "isKeyProject", "projectDomain",
			"projectStartDate", "projectEndDate", "role", "isKeyPosition",
			"yearsOfExperience", "mandatorySkills", "clientCommunication",
			"requestStartDate", "allocationEndDate" })
	public static class Record {

		@XmlElement(name = "RequestID")
		protected short requestID;
		@XmlElement(name = "ClientKey", required = true)
		protected String clientKey;
		@XmlElement(name = "ProjectKey", required = true)
		protected String projectKey;
		@XmlElement(name = "CustomerName", required = true)
		protected String customerName;
		@XmlElement(name = "ProjectName", required = true)
		protected String projectName;
		@XmlElement(name = "IsKeyProject", required = true)
		protected String isKeyProject;
		@XmlElement(name = "ProjectDomain")
		protected String projectDomain;
		@XmlElement(name = "ProjectStartDate", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date projectStartDate;
		@XmlElement(name = "ProjectEndDate", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date projectEndDate;
		@XmlElement(name = "Role", required = true)
		protected String role;
		@XmlElement(name = "IsKeyPosition", required = true)
		protected String isKeyPosition;
		@XmlElement(name = "YearsOfExperience", required = true)
		protected BigDecimal yearsOfExperience;
		@XmlElement(name = "MandatorySkills", required = true)
		protected String mandatorySkills;
		@XmlElement(name = "ClientCommunication", required = true)
		protected String clientCommunication;
		@XmlElement(name = "RequestStartDate", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date requestStartDate;
		@XmlElement(name = "AllocationEndDate", required = true)
		@XmlSchemaType(name = "date")
		@XmlJavaTypeAdapter(DateAdapter.class)
		protected Date allocationEndDate;

		/**
		 * Gets the value of the requestID property.
		 * 
		 */
		public short getRequestID() {
			return requestID;
		}

		/**
		 * Sets the value of the requestID property.
		 * 
		 */
		public void setRequestID(short value) {
			this.requestID = value;
		}

		/**
		 * Gets the value of the clientKey property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getClientKey() {
			return clientKey;
		}

		/**
		 * Sets the value of the clientKey property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setClientKey(String value) {
			this.clientKey = value;
		}

		/**
		 * Gets the value of the projectKey property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProjectKey() {
			return projectKey;
		}

		/**
		 * Sets the value of the projectKey property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProjectKey(String value) {
			this.projectKey = value;
		}

		/**
		 * Gets the value of the customerName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCustomerName() {
			return customerName;
		}

		/**
		 * Sets the value of the customerName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCustomerName(String value) {
			this.customerName = value;
		}

		/**
		 * Gets the value of the projectName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProjectName() {
			return projectName;
		}

		/**
		 * Sets the value of the projectName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProjectName(String value) {
			this.projectName = value;
		}

		/**
		 * Gets the value of the isKeyProject property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getIsKeyProject() {
			return isKeyProject;
		}

		/**
		 * Sets the value of the isKeyProject property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setIsKeyProject(String value) {
			this.isKeyProject = value;
		}

		/**
		 * Gets the value of the projectDomain property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProjectDomain() {
			return projectDomain;
		}

		/**
		 * Sets the value of the projectDomain property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProjectDomain(String value) {
			this.projectDomain = value;
		}

		/**
		 * Gets the value of the projectStartDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public Date getProjectStartDate() {
			return projectStartDate;
		}

		/**
		 * Sets the value of the projectStartDate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setProjectStartDate(Date value) {
			this.projectStartDate = value;
		}

		/**
		 * Gets the value of the projectEndDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public Date getProjectEndDate() {
			return projectEndDate;
		}

		/**
		 * Sets the value of the projectEndDate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setProjectEndDate(Date value) {
			this.projectEndDate = value;
		}

		/**
		 * Gets the value of the role property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRole() {
			return role;
		}

		/**
		 * Sets the value of the role property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRole(String value) {
			this.role = value;
		}

		/**
		 * Gets the value of the isKeyPosition property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getIsKeyPosition() {
			return isKeyPosition;
		}

		/**
		 * Sets the value of the isKeyPosition property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setIsKeyPosition(String value) {
			this.isKeyPosition = value;
		}

		/**
		 * Gets the value of the yearsOfExperience property.
		 * 
		 * @return possible object is {@link BigDecimal }
		 * 
		 */
		public BigDecimal getYearsOfExperience() {
			return yearsOfExperience;
		}

		/**
		 * Sets the value of the yearsOfExperience property.
		 * 
		 * @param value
		 *            allowed object is {@link BigDecimal }
		 * 
		 */
		public void setYearsOfExperience(BigDecimal value) {
			this.yearsOfExperience = value;
		}

		/**
		 * Gets the value of the mandatorySkills property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMandatorySkills() {
			return mandatorySkills;
		}

		/**
		 * Sets the value of the mandatorySkills property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMandatorySkills(String value) {
			this.mandatorySkills = value;
		}

		/**
		 * Gets the value of the clientCommunication property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getClientCommunication() {
			return clientCommunication;
		}

		/**
		 * Sets the value of the clientCommunication property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setClientCommunication(String value) {
			this.clientCommunication = value;
		}

		/**
		 * Gets the value of the requestStartDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public Date getRequestStartDate() {
			return requestStartDate;
		}

		/**
		 * Sets the value of the requestStartDate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setRequestStartDate(Date value) {
			this.requestStartDate = value;
		}

		/**
		 * Gets the value of the allocationEndDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public Date getAllocationEndDate() {
			return allocationEndDate;
		}

		/**
		 * Sets the value of the allocationEndDate property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setAllocationEndDate(Date value) {
			this.allocationEndDate = value;
		}

	}

}

class DateAdapter extends XmlAdapter<String, Date> {

	private final SimpleDateFormat dateFormat = new SimpleDateFormat(
			"dd-mm-YYYY");

	@Override
	public String marshal(Date v) throws Exception {
		synchronized (dateFormat) {
			return dateFormat.format(v);
		}
	}

	@Override
	public Date unmarshal(String v) throws Exception {
		synchronized (dateFormat) {
			return dateFormat.parse(v);
		}
	}

}